# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JibeMapNavigation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'JMapiOSSDK', :git => 'https://github.com/Jibestream/JMap-iOS-SDK-Pod.git'
  # Pods for JibeMapNavigation

  target 'JibeMapNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JibeMapNavigationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
