# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JibeMapBlueDot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'JMapiOSSDK', :git => 'https://github.com/Jibestream/JMap-iOS-SDK-Pod.git'

  # Pods for JibeMapBlueDot

  target 'JibeMapBlueDotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JibeMapBlueDotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
